=== svinent211/ExercicisLM/UD4/UD4ex3/UD4ex3_4.dtd
<!ELEMENT llistat (futur+, divisa+, bo+, lletra+)>
<!ELEMENT futur (producte_anterior, producte, mercat?)>
<!ATTLIST futur preu CDATA #REQUIRED>
<!ELEMENT producte_anterior EMPTY>
<!ATTLIST producte_anterior lloc (Madrid|Nova_York|Frankfurt|Tòquio) #REQUIRED>
<!ELEMENT producte (#PCDATA)>
<!ELEMENT mercat (#PCDATA)>

<!ELEMENT divisa (nom, producte_anterior, canvi+)>
<!ATTLIST divisa preu CDATA #REQUIRED
                 estable (si|no) #IMPLIED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT canvi (nom_moneda, tipus_canvi)>
<!ELEMENT nom_moneda (#PCDATA)>
<!ELEMENT tipus_canvi (#PCDATA)>

<!ELEMENT bo (producte_anterior, pais_de_procedencia, valor_desitjat, valor_minim, valor_maxim)>
<!ATTLIST bo preu CDATA #REQUIRED
             estable (si|no) #IMPLIED>
<!ELEMENT pais_de_procedencia (#PCDATA)>
<!ELEMENT valor_desitjat (#PCDATA)>
<!ELEMENT valor_minim (#PCDATA)>
<!ELEMENT valor_maxim (#PCDATA)>

<!ELEMENT lletra (producte_anterior, tipus_interes)>
<!ATTLIST lletra preu CDATA #REQUIRED>
<!ELEMENT tipus_interes (#PCDATA)>
<!ATTLIST lletra pais_emissor (Espanya|EUA|Alemanya|Japo) #REQUIRED>

=== svinent211/ExercicisLM/UD4/UD4ex3/UD4ex3_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistat SYSTEM "UD4ex3_4.dtd">

<llistat>
    <futur preu="">
        <producte_anterior lloc="Madrid"></producte_anterior>
        <producte></producte>
        <!-- Opcional -->
         <mercat></mercat>
    </futur>
    <divisa preu="" estable="no">
        <nom></nom>
        <producte_anterior lloc="Madrid"></producte_anterior>
        <canvi>
            <nom_moneda></nom_moneda>
            <tipus_canvi></tipus_canvi>
        </canvi>       
    </divisa>
    <bo preu="" estable="si">
        <producte_anterior lloc="Madrid"/>
        <pais_de_procedencia>Espanya</pais_de_procedencia>
        <valor_desitjat></valor_desitjat>
        <valor_minim></valor_minim>
        <valor_maxim></valor_maxim>
    </bo>
    <lletra preu="" pais_emissor="Espanya">
        <producte_anterior lloc="Madrid"></producte_anterior>
        <tipus_interes>3</tipus_interes>
    </lletra>
</llistat>
