=== svinent211/ExercicisLM/UD4/UD4ex3/UD4ex3_2.dtd
<!ELEMENT llistacursos (professors+, assignatures+, cursos+)>
<!ELEMENT professors (professor+)>
<!ELEMENT professor (nom, cognom1, cognom2?)>
<!ATTLIST professor NRP ID #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom1 (#PCDATA)>
<!ELEMENT cognom2 (#PCDATA)>

<!ELEMENT assignatures (assignatura+)>
<!ELEMENT assignatura (nom)>
<!ATTLIST assignatura codi_assignatura ID #REQUIRED
                        NRP IDREF #REQUIRED>

<!ELEMENT cursos (curs+)>
<!ELEMENT curs (alumne+)>
<!ATTLIST curs any_academic CDATA #REQUIRED>
<!ELEMENT alumne (dni, nom, cognom1, cognom2?, llista_assignatures)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT llista_assignatures (REFassignatura+)>
<!ELEMENT REFassignatura EMPTY>
<!ATTLIST REFassignatura codi_assignatura IDREF #REQUIRED>

=== svinent211/ExercicisLM/UD4/UD4ex3/UD4ex3_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistacursos SYSTEM "UD4ex3_2.dtd">
<llistacursos>
    <professors>
        <professor NRP="ir">
            <nom>Irene</nom>
            <cognom1>Vinent</cognom1>
            <!-- Opcional -->
            <cognom2>Mercadal</cognom2>
        </professor>
        <professor NRP="mi">
            <nom>Miquel</nom>
            <cognom1>Petrus</cognom1>
        </professor>
    </professors>
    <assignatures>
        <assignatura codi_assignatura="lm" NRP="ir">
            <nom>LM</nom>
        </assignatura>
        <assignatura codi_assignatura="ed" NRP="mi">
            <nom>ED</nom>
        </assignatura>
    </assignatures>
    <cursos>
        <curs any_academic="2025">
            <alumne>
                <dni>40000000Q</dni>
                <nom>Sergi</nom>
                <cognom1>Vinent</cognom1>
                <!-- Opcional -->
                <cognom2>Sintes</cognom2>
                <!-- Empra el codi creat abans a assignatures-->
                <llista_assignatures >
                    <REFassignatura codi_assignatura="lm"/>
                    <REFassignatura codi_assignatura="ed"/>
                </llista_assignatures>
            </alumne>
        </curs>
    </cursos>
</llistacursos>
