=== svinent211/ExercicisLM/UD4/UD4ex4_2/4.1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="capcalera">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="capcalera_id" type="xs:NMTOKEN"/>
                            <xs:element name="data">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                    <xs:minInclusive value="1"></xs:minInclusive>
                                                    <xs:maxInclusive value="31"></xs:maxInclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="mes">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                    <xs:minInclusive value="1"></xs:minInclusive>
                                                    <xs:maxInclusive value="12"></xs:maxInclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="any" type="xs:positiveInteger"></xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="client" type="dades_type"/>

                            <xs:element name="proveidor" type="dades_type"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="linea" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="article">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="descripcio_producte" type="xs:string"/>
                                        <xs:element name="preu_sense_iva" type="xs:double"/>
                                        <xs:element name="preu_amb_iva" type="xs:double"/>
                                    </xs:sequence>
                                    <xs:attribute name="id_article" type="xs:ID" use="required"/>
                                    <xs:attribute name="tipus_iva" type="tipus_iva_type" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="unitats" type="xs:integer"/>
                            <xs:element name="import_total" type="xs:double"/>
                        </xs:sequence>
                        <!-- Atributs -->
                         <xs:attribute name="id" type="xs:ID" use="required"/>
                         <xs:attribute name="article_ref" type="xs:IDREF" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="resum_total">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subtotal_4" type="xs:double"/>
                            <xs:element name="subtotal_10" type="xs:double"/>
                            <xs:element name="subtotal_21" type="xs:double"/>
                            <xs:element name="total_sense_iva" type="xs:double"/>
                            <xs:element name="total_amb_iva" type="xs:double"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
            <xs:complexType name="dades_type">
                <xs:sequence>
                    <xs:element name="nom_fiscal" type="xs:string"/>
                    <xs:element name="nom_comercial" type="xs:string" minOccurs="0"/>
                    <xs:element name="NIF" type="xs:NMTOKEN" />
                </xs:sequence>
            </xs:complexType>

            <xs:simpleType name="tipus_iva_type">
                <xs:restriction base="xs:positiveInteger">
                    <xs:enumeration value="4"></xs:enumeration>
                    <xs:enumeration value="10"></xs:enumeration>
                    <xs:enumeration value="21"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
</xs:schema>

=== svinent211/ExercicisLM/UD4/UD4ex4_2/4.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="4.1.xsd">
    <capcalera>
        <capcalera_id>S</capcalera_id>
        <data>
            <dia>1</dia>
            <mes>3</mes>
            <any>2026</any>
        </data>
        <client>
            <nom_fiscal>IES Joan Ramis i Ramis</nom_fiscal>
            <!-- No ha fet falta posar nom_comercial perque és opcional-->
            <nom_comercial>IES Joan Ramis i Ramis</nom_comercial>
            <NIF>X09363693</NIF>
        </client>
        <proveidor>
            <nom_fiscal>Planeta</nom_fiscal>
            <!-- No ha fet falta posar nom_comercial perque és opcional-->
            <NIF>X11363653</NIF>
        </proveidor>
    </capcalera>
    <linea article_ref="A1" id="L1"> 
        <article id_article="A1" tipus_iva="21">
            <descripcio_producte>Don Quijote de la Mancha</descripcio_producte>
            <preu_sense_iva>20</preu_sense_iva>
            <preu_amb_iva>24.2</preu_amb_iva>
        </article>
        <unitats>10</unitats>
        <import_total>242</import_total>
    </linea>
    <linea article_ref="A2" id="L2">
        <article id_article="A2" tipus_iva="21">
            <descripcio_producte>El secret del meu turbant</descripcio_producte>
            <preu_sense_iva>15</preu_sense_iva>
            <preu_amb_iva>18.15</preu_amb_iva>
        </article>
        <unitats>20</unitats>
        <import_total>363</import_total>
    </linea>
    <resum_total>
        <subtotal_4>0</subtotal_4>
        <subtotal_10>0</subtotal_10>
        <subtotal_21>0</subtotal_21>
        <total_sense_iva>500</total_sense_iva>
        <total_amb_iva>605</total_amb_iva>
    </resum_total>
</factura>
