=== svinent211/ExercicisLM/UD4/UD4ProbaDTD/4.1.dtd
<!ELEMENT factura (capcalera, linea+, resum_total)>

<!ELEMENT capcalera (data, client, proveidor)>
<!ATTLIST capcalera id NMTOKEN #REQUIRED>
    <!ELEMENT data EMPTY>
        <!ATTLIST data dia CDATA #REQUIRED
                       mes CDATA #REQUIRED
                       any CDATA #REQUIRED>
    <!ELEMENT client EMPTY>
        <!ATTLIST client nom_fiscal CDATA #REQUIRED
                         nom_comercial CDATA #IMPLIED
                         NIF CDATA #REQUIRED>
    <!ELEMENT proveidor EMPTY>
        <!ATTLIST proveidor nom_fiscal CDATA #REQUIRED
                            nom_comercial CDATA #IMPLIED
                            NIF CDATA #REQUIRED>

<!ELEMENT linea (article, unitats, import_total)>
    <!ATTLIST linea article_ref IDREF #REQUIRED
                    id_linea NMTOKEN #REQUIRED>
    <!ELEMENT article (descripcio_producte, preu_sense_iva, preu_amb_iva)>
        <!ATTLIST article id_article ID #REQUIRED
                          tipus_iva (4|10|21) #REQUIRED>
    <!ELEMENT descripcio_producte (#PCDATA)>
    <!ELEMENT preu_sense_iva (#PCDATA)>
    <!ELEMENT preu_amb_iva (#PCDATA)>
    <!ELEMENT unitats (#PCDATA)>
    <!ELEMENT import_total (#PCDATA)>

<!ELEMENT resum_total (subtotal_4, subtotal_10, subtotal_21, total_sense_iva, total_amb_iva)>
    <!ELEMENT subtotal_4 (#PCDATA)>
    <!ELEMENT subtotal_10 (#PCDATA)> 
    <!ELEMENT subtotal_21 (#PCDATA)>
    <!ELEMENT total_sense_iva (#PCDATA)>
    <!ELEMENT total_amb_iva (#PCDATA)>

=== svinent211/ExercicisLM/UD4/UD4ProbaDTD/4.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "4.1.dtd">
<factura>
    <capcalera id="A1">
        <data dia="9" mes="3" any="2026"/>
        <!-- No ha fet falta posar nom_comercial perque és opcional-->
        <client nom_fiscal="IES Joan Ramis i Ramis"  NIF="X09363693"/>
        <proveidor nom_fiscal="Planeta" nom_comercial="Planeta" NIF="X70602583"/>
    </capcalera>
    <linea article_ref="L1" id_linea="B1">
        <article id_article="L1" tipus_iva="21">
            <descripcio_producte>Don Quijote de la Mancha</descripcio_producte>
            <preu_sense_iva>20</preu_sense_iva>
            <preu_amb_iva>24,2</preu_amb_iva>
        </article>
        <unitats>10</unitats>
        <import_total>242</import_total>
    </linea>
    <linea article_ref="L2" id_linea="B2">
        <article id_article="L2" tipus_iva="21">
            <descripcio_producte>El secret del meu turbant</descripcio_producte>
            <preu_sense_iva>15</preu_sense_iva>
            <preu_amb_iva>18,15</preu_amb_iva>
        </article>
        <unitats>20</unitats>
        <import_total>363</import_total>
    </linea>
    <resum_total>
        <subtotal_4>0</subtotal_4>
        <subtotal_10>0</subtotal_10>
        <subtotal_21></subtotal_21>
        <total_sense_iva>500</total_sense_iva>
        <total_amb_iva>605</total_amb_iva>
    </resum_total>
</factura>
